# Generated by Django 4.2 on 2023-04-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo Curso')),
                ('description', models.TextField(verbose_name='Descrição do Curso')),
                ('h1', models.CharField(max_length=100, verbose_name='Header Principal (h1) da Página')),
                ('h2', models.TextField(verbose_name='Header Secundário (h2) da Página')),
                ('beneficios', models.TextField(verbose_name='Benefícios do Curso')),
                ('faq', models.TextField(verbose_name='Perguntas Frequentes')),
            ],
        ),
    ]
