# Generated by Django 4.2 on 2023-05-18 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_faqgeral_options_remove_curso_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='urlVenda',
            field=models.URLField(blank=True, null=True, verbose_name='Link da página de checkout da Hotmart referente ao curso (pay.hotmart.com)'),
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='alunos')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome do aluno')),
                ('profissao', models.CharField(max_length=100, null=True, verbose_name='Profissão')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
